### ISSUE TITLE
Cheat menu cut off

### ISSUE THREAD

**Issue by iNeedSteamAccounts** [spirthack/CSGOSimple#63] opened 2019-06-12 16:20 UTC
When I press insert only the upper ~30 pixels of my cheat-menu get visible, the rest is cut off. Why is that? I can still scroll though everything, but I don't even see a complete button but only a part of it...

**Comment by SrMilton** [comment] 2019-06-17 04:03
me 2

**Comment by xAkiraMiura** [comment] 2019-06-19 02:23
in my experience this only seems to happen when I inject too early, maybe try injecting when the main menu is ready and shows the ct/t?

**Comment by SrMilton** [comment] 2019-06-19 17:15
The problem is with the fullscreen mode.

**Comment by anarh1st47** [comment] 2019-07-27 13:13
can u record video?

**Comment by SrMilton** [comment] 2019-07-27 14:54
@anarh1st47 https://youtu.be/Q-KrfTSI24k

**Comment by xAkiraMiura** [comment] 2019-07-27 14:58
that looks like the height is really low, when i got the problem if i moved it around then it gets hidden behind an invisible layer.

**Comment by anarh1st47** [comment] 2019-07-27 15:44
Whats your video settings?

**Comment by SrMilton** [comment] 2019-07-27 16:01
works fine in widescreen. 16:9 1600x900

**Comment by privileged8222** [comment] 2019-07-29 22:07
CTRL + SHIFT + F, look for 'ImGuiWindowFlags_NoResize' and remove it along with the |. it should look like this when done:

https://gyazo.com/452fa7944380a41911a7d73651d99b2c

this allows you to resize the menu how you like :)

**Comment by SrMilton** [comment] 2019-07-30 00:22
> CTRL + SHIFT + F, look for 'ImGuiWindowFlags_NoResize' and remove it along with the |. it should look like this when done:
> 
> https://gyazo.com/452fa7944380a41911a7d73651d99b2c
> 
> this allows you to resize the menu how you like :)

Yeh, i know but this is not the solution :(

**Comment by Kron1Q** [comment] 2019-08-04 01:11
menu.cpp, ImGui::SetNextWindowSize(ImVec2{ 1000, 0 }, ImGuiSetCond_Once);

increase to, idk 1000, 500 and u are gucci

**Comment by anarh1st47** [comment] 2019-08-09 22:06
should be fixed, feel free reopen if still exists

**Closed by anarh1st47** 2019-08-09 22:06 UTC
